# Copyright (c) 2026 SPHARX. All Rights Reserved.
# Kubernetes Namespace for AgentRT gateway Module
# Version: 0.1.0

apiVersion: v1
kind: Namespace
metadata:
  name: agentrt-gateway
  labels:
    name: agentrt-gateway
    app.kubernetes.io/name: agentos
    app.kubernetes.io/component: gateway
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "AgentRT gateway Module Namespace"
